"use client"

import { useRouter } from "next/navigation";

type ReportProps = {
  isVerified?: boolean;
};

export function Posts() {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 w-full">
      <Report isVerified={true} />
      <Report isVerified={true} />
    </div>
  );
}

function Report({ isVerified }: ReportProps) {

const router = useRouter();

  return (
    <div onClick={() => router.push("/community/5e7a72e1-b5d0-4281-a7b6-eb464605885b")} className="flex w-full flex-col flex-wrap gap-5 p-6 border border-[#E4E4E4] rounded-xl">
      <div className="flex justify-between flex-wrap">
        <p className=" text-[20px] font-semibold text-primary">
          2024 TESLA MODEL Y PERFORMANCE
        </p>{" "}
        <p className="text-[#4D4D4D]">2 minutes ago</p>
      </div>
      <div className="flex gap-5 items-center flex-wrap">
        <p className="text-[#1C1C1C] text-[24px] font-semibold">
          2T1BURHE5JC****
        </p>
        <p className="rounded-full text-primary px-5 py-0.5 bg-[#F8F0FF] font-semibold">
          VIN
        </p>
      </div>

      <div className="flex gap-2 flex-col sm:flex-row">
        <div className="flex-1 flex flex-col gap-1">
          <p className="flex gap-4">
            <span className="text-[#999999]"> Make: </span>{" "}
            <span className="text-[#1C1C1C]"> Tesla</span>
          </p>
          <p className="flex gap-3">
            <span className="text-[#999999]"> Model: </span>{" "}
            <span className="text-[#1C1C1C]"> Model Y Performance</span>
          </p>
          <p className="flex gap-6">
            <span className="text-[#999999]"> Year: </span>{" "}
            <span className="text-[#1C1C1C]"> 2024</span>
          </p>
          <div className="px-[12px] py-2 rounded-sm bg-[#F7EEFF] mt-2">
            <p className="text-primary text-[15px]">
              “Clean vehicle, price looks fair.”
            </p>
          </div>
        </div>
        <div onClick={()=> router.push("/community/profile")} className="flex-1 flex flex-col gap-[12px]">
          <span className="text-[#999999]">Generated by:</span>
          <div className="flex items-center gap-2">
            <div className="rounded-full overflow-hidden mr-2">
              <img width={40} src="/community/user.png" alt="User" />
            </div>
            <span className="text-[#1C1C1C] font-semibold">
              @AutoMasterPro{" "}
            </span>
            {isVerified && (
              <img src="/community/verified-20.svg" alt="Verified" />
            )}
          </div>
        </div>
      </div>

      <div className="flex gap-2 justify-end">
        <button className="font-fredoka text-[20px] font-semibold text-primary rounded-full px-4 py-2 sm:px-8 sm:py-[12px] border border-primary">
          Chat with Dealer
        </button>
        <div className="flex gap-2 items-center">
          <img width={25} src="/community/red-like-25.svg" alt="like" />
          <p>{9}</p>
        </div>
      </div>
    </div>
  );
}
