"use client";

import { Posts } from "./community-post";
import { useRouter } from "next/navigation";
export default function CommunityReportsDetails() {
  return (
    <div>
      <div className="layout px-8 pt-10 sm:px-10 lg:px-20 lg:pt-16 flex gap-16">
        <div className="flex-1">
          <ReportDetails isVerified={true} />
          <div className="w-full h-0.5 my-8 bg-[#EAEAEA]"></div>

          <p className="text-[24px] text-[#1C1C1C] font-semibold mb-8">
            Vehicle Summary
          </p>

          <div className="flex flex-col gap-3">
            <div className="font-semibold text-[#1C1C1C] text-[18px] flex gap-8 w-[50%] justify-between">
              <p>Fields</p>
              <p>Details</p>
            </div>

            <div className=" text-[#1C1C1C] text-[18px] flex gap-8 w-[50%] justify-between">
              <p>Make</p>
              <p>Honda</p>
            </div>

            <div className=" text-[#1C1C1C] text-[18px] flex gap-8 w-[50%] justify-between">
              <p>Model</p>
              <p>Accord</p>
            </div>

            <div className="font-semibold text-[#1C1C1C] text-[18px] flex gap-8 w-[50%] justify-between">
              <p>Market Value </p>
              <p>1200</p>
            </div>
          </div>

          <div className="w-full h-0.5 my-8 bg-[#EAEAEA]"></div>
          <div>
            <p className="text-[24px] text-[#1C1C1C] font-semibold mb-8">
              Report Summary
            </p>
            <p className="text-[18px] text-[1C1C1C] mb-[12px]">Report Type</p>
            <p className="text-[18px] text-[1C1C1C] font-semibold mb-6">
              Car History Report
            </p>
            <p className="text-[18px] text-[1C1C1C] mb-[12px]">
              Report Includes
            </p>

            <ol className="list-disc list-inside text-[18px] font-semibold space-y-2">
              {[
                "Ownership History",
                "Title & Accident Check",
                "Service Records",
                "Recall Notices",
                "Market Valuation",
                "Resale Suggestions",
              ].map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ol>
          </div>

          <div className="flex items-center font-semibold gap-2 sm:gap-8 my-8 sm:my-10">
            <div className="w-full h-0.5 my-8 bg-primary"></div>
            <p className="whitespace-nowrap text-[20px] sm:text-[32px]">Other Reports</p>
            <div className="w-full h-0.5 my-8 bg-primary"></div>
          </div>
           <Posts/>
        </div>
      </div>
    </div>
  );
}

type ReportProps = {
  isVerified?: boolean;
};

function ReportDetails({ isVerified }: ReportProps) {

  const router = useRouter();

  return (
    <div className="flex flex-col gap-4">
      <div className="flex justify-between flex-wrap">
        <p className=" text-[24px] font-semibold text-primary">
          2024 TESLA MODEL Y PERFORMANCE
        </p>{" "}
        <p className="text-[#4D4D4D]">2 minutes ago</p>
      </div>
      <div className="flex gap-5 items-center">
        <p className="text-[#1C1C1C] text-[24px] font-semibold">
          2T1BURHE5JC****
        </p>
        <p className="rounded-full text-primary px-5 py-0.5 bg-[#F8F0FF] font-semibold">
          VIN
        </p>
      </div>

      <p className="text-[#4D4D4D] text-[18px]">
        Clean vehicle with no major issues found. The overall condition seems
        well-maintained, and the listed price appears fair based on current
        market trends.
      </p>

      <div className="flex justify-between  sm:items-center flex-wrap flex-col sm:flex-row  w-full gap-4 ">
        <div className="flex-1 flex flex-col gap-[12px]">
          <span className="text-[#999999]">Generated by:</span>
          <div onClick={()=> router.push("/community/profile")} className="flex items-center gap-2">
            <div className="rounded-full overflow-hidden mr-2">
              <img width={40} src="/community/user.png" alt="User" />
            </div>
            <span className="text-[#1C1C1C] font-semibold">
              @AutoMasterPro{" "}
            </span>
            {isVerified && (
              <img src="/community/verified-20.svg" alt="Verified" />
            )}
          </div>
        </div>
        <button className="font-fredoka text-[20px] font-semibold text-primary w-fit rounded-full px-6 py-2 sm:px-8 sm:py-[12px] border border-primary">
          Chat with Dealer
        </button>
      </div>
    </div>
  );
}
