"use client"

import { useRouter } from "next/navigation";

type ReportProps = {
  isVerified?: boolean;
};

export function Posts() {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 w-full">
      <Report isVerified={true} />
      <Report isVerified={true} />
    </div>
  );
}

function Report({ isVerified }: ReportProps) {

const router = useRouter();

  return (
    <div className="flex w-full flex-col flex-wrap gap-5 p-6 border shadow-md border-[#E4E4E4] rounded-xl">
      <div className="flex justify-between flex-wrap">
        <p className=" text-[18px] font-semibold text-primary">
          2024 TESLA MODEL Y PERFORMANCE
        </p>{" "}
        <p className="text-[#4D4D4D] text-sm">2 minutes ago</p>
      </div>
      <div className="flex gap-5 items-center flex-wrap">
        <p className="text-[#1C1C1C] text-[18px] font-semibold">
          2T1BURHE5JC****
        </p>
        <p className="rounded-full text-primary px-5 py-0.5 bg-[#F8F0FF] font-semibold text-md">
          VIN
        </p>
      </div>

      <div className="flex gap-2 flex-col sm:flex-row">
        <div className="flex-1 flex flex-col gap-1">
          <p className="flex gap-4 text-sm">
            <span className="text-[#999999]"> Make: </span>{" "}
            <span className="text-[#1C1C1C]"> Tesla</span>
          </p>
          <p className="flex gap-3 text-sm">
            <span className="text-[#999999]"> Model: </span>{" "}
            <span className="text-[#1C1C1C]"> Model Y Performance</span>
          </p>
          <p className="flex gap-6 text-sm">
            <span className="text-[#999999]"> Year: </span>{" "}
            <span className="text-[#1C1C1C]"> 2024</span>
          </p>
          <div className="px-[12px] py-2 rounded-sm bg-[#F7EEFF] mt-2">
            <p className="text-primary text-[14px]">
              “ Clean vehicle, price looks fair. ”
            </p>
          </div>
        </div>
        <div onClick={()=> router.push("/community/profile")} className="flex-1 flex flex-col gap-[12px]">
          <span className="text-[#999999] text-sm">Generated by:</span>
          <div className="flex items-center gap-2">
            <div className="rounded-full overflow-hidden mr-2">
              <img width={40} src="/community/user.png" alt="User" />
            </div>
            <span className="text-[#1C1C1C] font-semibold text-sm">
              @AutoMasterPro{" "}
            </span>
            {isVerified && (
              <img src="/community/verified-20.svg" alt="Verified" />
            )}
          </div>
        </div>
      </div>

      {/*<div className="flex gap-2 justify-end">
        <button className="font-fredoka text-[15px] font-semibold text-primary rounded-full px-4 sm:px-8 py-2 border border-primary">
          Chat with Dealer
        </button> 
      </div>*/}
    </div>
  );
}
